export {
  HEADPHONES_SCHEMA,
  HEADPHONES_FIELD_GROUPS,
  HEADPHONES_REQUIRED_KEYS,
  EARBUDS_SCHEMA,
  EARBUDS_FIELD_GROUPS,
  EARBUDS_REQUIRED_KEYS,
  BLUETOOTH_SPEAKER_SCHEMA,
  BLUETOOTH_SPEAKER_FIELD_GROUPS,
  BLUETOOTH_SPEAKER_REQUIRED_KEYS
} from "../../listingSchemas";
