export {
  LAPTOP_SCHEMA,
  LAPTOP_FIELD_GROUPS,
  LAPTOP_REQUIRED_KEYS,
  DESKTOP_COMPUTER_SCHEMA,
  DESKTOP_COMPUTER_FIELD_GROUPS,
  DESKTOP_COMPUTER_REQUIRED_KEYS,
  MONITOR_SCHEMA,
  MONITOR_FIELD_GROUPS,
  MONITOR_REQUIRED_KEYS
} from "../../listingSchemas";
