import type { ListingItemConfig } from "../core.js";

import {
  SMARTPHONE_SCHEMA,
  SMARTPHONE_FIELD_GROUPS,
  SMARTPHONE_REQUIRED_KEYS,
  FEATURE_PHONE_SCHEMA,
  FEATURE_PHONE_FIELD_GROUPS,
  FEATURE_PHONE_REQUIRED_KEYS,
  TABLET_SCHEMA,
  TABLET_FIELD_GROUPS,
  TABLET_REQUIRED_KEYS,
  SMARTWATCH_FITNESS_BAND_SCHEMA,
  SMARTWATCH_FITNESS_BAND_FIELD_GROUPS,
  SMARTWATCH_FITNESS_BAND_REQUIRED_KEYS,
} from "./phones.js";

import {
  LAPTOP_SCHEMA,
  LAPTOP_FIELD_GROUPS,
  LAPTOP_REQUIRED_KEYS,
  DESKTOP_COMPUTER_SCHEMA,
  DESKTOP_COMPUTER_FIELD_GROUPS,
  DESKTOP_COMPUTER_REQUIRED_KEYS,
  MONITOR_SCHEMA,
  MONITOR_FIELD_GROUPS,
  MONITOR_REQUIRED_KEYS,
} from "./computers.js";

import {
  HEADPHONES_SCHEMA,
  HEADPHONES_FIELD_GROUPS,
  HEADPHONES_REQUIRED_KEYS,
  EARBUDS_SCHEMA,
  EARBUDS_FIELD_GROUPS,
  EARBUDS_REQUIRED_KEYS,
  BLUETOOTH_SPEAKER_SCHEMA,
  BLUETOOTH_SPEAKER_FIELD_GROUPS,
  BLUETOOTH_SPEAKER_REQUIRED_KEYS,
} from "./audio.js";

import {
  POWER_BANK_SCHEMA,
  POWER_BANK_FIELD_GROUPS,
  POWER_BANK_REQUIRED_KEYS,
  CHARGER_CHARGING_ADAPTER_SCHEMA,
  CHARGER_CHARGING_ADAPTER_FIELD_GROUPS,
  CHARGER_CHARGING_ADAPTER_REQUIRED_KEYS,
  ROUTER_MIFI_MODEM_SCHEMA,
  ROUTER_MIFI_MODEM_FIELD_GROUPS,
  ROUTER_MIFI_MODEM_REQUIRED_KEYS,
} from "./power.js";

import {
  USB_FLASH_DRIVE_SCHEMA,
  USB_FLASH_DRIVE_FIELD_GROUPS,
  USB_FLASH_DRIVE_REQUIRED_KEYS,
  MEMORY_CARD_SCHEMA,
  MEMORY_CARD_FIELD_GROUPS,
  MEMORY_CARD_REQUIRED_KEYS,
  EXTERNAL_HARD_DRIVE_SSD_SCHEMA,
  EXTERNAL_HARD_DRIVE_SSD_FIELD_GROUPS,
  EXTERNAL_HARD_DRIVE_SSD_REQUIRED_KEYS,
  KEYBOARD_SCHEMA,
  KEYBOARD_FIELD_GROUPS,
  KEYBOARD_REQUIRED_KEYS,
  MOUSE_SCHEMA,
  MOUSE_FIELD_GROUPS,
  MOUSE_REQUIRED_KEYS,
} from "./storage.js";

import {
  PRINTER_SCHEMA,
  PRINTER_FIELD_GROUPS,
  PRINTER_REQUIRED_KEYS,
  CALCULATOR_SCHEMA,
  CALCULATOR_FIELD_GROUPS,
  CALCULATOR_REQUIRED_KEYS,
} from "./studentTools.js";

export * from "./phones.js";
export * from "./computers.js";
export * from "./audio.js";
export * from "./power.js";
export * from "./storage.js";
export * from "./studentTools.js";

export const ELECTRONICS_LISTING_ITEM_CONFIGS: ListingItemConfig[] = [
  {
    schema: SMARTPHONE_SCHEMA,
    fieldGroups: SMARTPHONE_FIELD_GROUPS,
    requiredKeys: SMARTPHONE_REQUIRED_KEYS,
  },
  {
    schema: FEATURE_PHONE_SCHEMA,
    fieldGroups: FEATURE_PHONE_FIELD_GROUPS,
    requiredKeys: FEATURE_PHONE_REQUIRED_KEYS,
  },
  {
    schema: TABLET_SCHEMA,
    fieldGroups: TABLET_FIELD_GROUPS,
    requiredKeys: TABLET_REQUIRED_KEYS,
  },
  {
    schema: SMARTWATCH_FITNESS_BAND_SCHEMA,
    fieldGroups: SMARTWATCH_FITNESS_BAND_FIELD_GROUPS,
    requiredKeys: SMARTWATCH_FITNESS_BAND_REQUIRED_KEYS,
  },

  {
    schema: LAPTOP_SCHEMA,
    fieldGroups: LAPTOP_FIELD_GROUPS,
    requiredKeys: LAPTOP_REQUIRED_KEYS,
  },
  {
    schema: DESKTOP_COMPUTER_SCHEMA,
    fieldGroups: DESKTOP_COMPUTER_FIELD_GROUPS,
    requiredKeys: DESKTOP_COMPUTER_REQUIRED_KEYS,
  },
  {
    schema: MONITOR_SCHEMA,
    fieldGroups: MONITOR_FIELD_GROUPS,
    requiredKeys: MONITOR_REQUIRED_KEYS,
  },

  {
    schema: HEADPHONES_SCHEMA,
    fieldGroups: HEADPHONES_FIELD_GROUPS,
    requiredKeys: HEADPHONES_REQUIRED_KEYS,
  },
  {
    schema: EARBUDS_SCHEMA,
    fieldGroups: EARBUDS_FIELD_GROUPS,
    requiredKeys: EARBUDS_REQUIRED_KEYS,
  },
  {
    schema: BLUETOOTH_SPEAKER_SCHEMA,
    fieldGroups: BLUETOOTH_SPEAKER_FIELD_GROUPS,
    requiredKeys: BLUETOOTH_SPEAKER_REQUIRED_KEYS,
  },

  {
    schema: POWER_BANK_SCHEMA,
    fieldGroups: POWER_BANK_FIELD_GROUPS,
    requiredKeys: POWER_BANK_REQUIRED_KEYS,
  },
  {
    schema: CHARGER_CHARGING_ADAPTER_SCHEMA,
    fieldGroups: CHARGER_CHARGING_ADAPTER_FIELD_GROUPS,
    requiredKeys: CHARGER_CHARGING_ADAPTER_REQUIRED_KEYS,
  },
  {
    schema: ROUTER_MIFI_MODEM_SCHEMA,
    fieldGroups: ROUTER_MIFI_MODEM_FIELD_GROUPS,
    requiredKeys: ROUTER_MIFI_MODEM_REQUIRED_KEYS,
  },

  {
    schema: USB_FLASH_DRIVE_SCHEMA,
    fieldGroups: USB_FLASH_DRIVE_FIELD_GROUPS,
    requiredKeys: USB_FLASH_DRIVE_REQUIRED_KEYS,
  },
  {
    schema: MEMORY_CARD_SCHEMA,
    fieldGroups: MEMORY_CARD_FIELD_GROUPS,
    requiredKeys: MEMORY_CARD_REQUIRED_KEYS,
  },
  {
    schema: EXTERNAL_HARD_DRIVE_SSD_SCHEMA,
    fieldGroups: EXTERNAL_HARD_DRIVE_SSD_FIELD_GROUPS,
    requiredKeys: EXTERNAL_HARD_DRIVE_SSD_REQUIRED_KEYS,
  },
  {
    schema: KEYBOARD_SCHEMA,
    fieldGroups: KEYBOARD_FIELD_GROUPS,
    requiredKeys: KEYBOARD_REQUIRED_KEYS,
  },
  {
    schema: MOUSE_SCHEMA,
    fieldGroups: MOUSE_FIELD_GROUPS,
    requiredKeys: MOUSE_REQUIRED_KEYS,
  },

  {
    schema: PRINTER_SCHEMA,
    fieldGroups: PRINTER_FIELD_GROUPS,
    requiredKeys: PRINTER_REQUIRED_KEYS,
  },
  {
    schema: CALCULATOR_SCHEMA,
    fieldGroups: CALCULATOR_FIELD_GROUPS,
    requiredKeys: CALCULATOR_REQUIRED_KEYS,
  },
];
