export {
  SMARTPHONE_SCHEMA,
  SMARTPHONE_FIELD_GROUPS,
  SMARTPHONE_REQUIRED_KEYS,
  FEATURE_PHONE_SCHEMA,
  FEATURE_PHONE_FIELD_GROUPS,
  FEATURE_PHONE_REQUIRED_KEYS,
  TABLET_SCHEMA,
  TABLET_FIELD_GROUPS,
  TABLET_REQUIRED_KEYS,
  SMARTWATCH_FITNESS_BAND_SCHEMA,
  SMARTWATCH_FITNESS_BAND_FIELD_GROUPS,
  SMARTWATCH_FITNESS_BAND_REQUIRED_KEYS
} from "../../listingSchemas";
