export {
  POWER_BANK_SCHEMA,
  POWER_BANK_FIELD_GROUPS,
  POWER_BANK_REQUIRED_KEYS,
  CHARGER_CHARGING_ADAPTER_SCHEMA,
  CHARGER_CHARGING_ADAPTER_FIELD_GROUPS,
  CHARGER_CHARGING_ADAPTER_REQUIRED_KEYS,
  ROUTER_MIFI_MODEM_SCHEMA,
  ROUTER_MIFI_MODEM_FIELD_GROUPS,
  ROUTER_MIFI_MODEM_REQUIRED_KEYS
} from "../../listingSchemas";
