export {
  USB_FLASH_DRIVE_SCHEMA,
  USB_FLASH_DRIVE_FIELD_GROUPS,
  USB_FLASH_DRIVE_REQUIRED_KEYS,
  MEMORY_CARD_SCHEMA,
  MEMORY_CARD_FIELD_GROUPS,
  MEMORY_CARD_REQUIRED_KEYS,
  EXTERNAL_HARD_DRIVE_SSD_SCHEMA,
  EXTERNAL_HARD_DRIVE_SSD_FIELD_GROUPS,
  EXTERNAL_HARD_DRIVE_SSD_REQUIRED_KEYS
} from "../../listingSchemas";
