import { type HeaderChip } from "../constants";
import {
  ABOUT_PATH, ACCOUNT_SETUP_PATH, ADMIN_AUDIT_PATH, ADMIN_BALANCE_PATH, ADMIN_DISPUTES_PATH, ADMIN_MODERATION_QUEUE_PATH, ADMIN_PATH,
  ADMIN_MESSAGES_PATH, ADMIN_PAYOUT_DESTINATIONS_PATH, ADMIN_PAYOUTS_PATH, ADMIN_PAYMENTS_PATH, ADMIN_REPORTS_PATH,
  ADMIN_SELLER_APPLICATIONS_PATH, ADMIN_SETUP_PATH, ADMIN_TRANSACTION_INSPECTOR_PATH,
  BECOME_SELLER_PATH, CHANGE_EMAIL_PATH, CHANGE_PASSWORD_PATH, CREATE_PATH, EDIT_ACCOUNT_PATH, EDIT_PATH, EDIT_PROFILE_PATH,
  EMAIL_ACTION_PATH, EXPLORE_PATH, FORGOT_PASSWORD_PATH, HIDDEN_PATH, LISTING_PATH, LOGIN_PATH, MARKET_CHIP_PATHS,
  MESSAGES_PATH, MY_LISTINGS_PATH, PAYMENT_RETURN_PATH, PRIVACY_PATH, PROFILE_PATH, REPORT_PATH, SAVED_PATH, SAFETY_PATH,
  SELLER_DASHBOARD_PATH, SELLER_ORDERS_PATH, SELLER_PATH, SELLER_PAYOUTS_PATH, SETTINGS_PATH, SIGNUP_PATH, TERMS_PATH,
  VERIFY_EMAIL_PATH, EVENTS_MANAGE_PATH, EVENTS_DASHBOARD_PATH, ADMIN_EVENTS_PATH, TICKETS_PATH, type AppRoute,
} from "./appNavigation.paths";
export type ExploreQueryState={search:string;university:string;category:string;subcategory:string;itemType:string;status:string;condition:string;sortBy:string;minPrice:string;maxPrice:string;hideSoldOut:boolean;page:number;specFilters:Record<string,string|string[]|boolean>};
const EXPLORE_QUERY_KEYS=["search","university","category","subcategory","itemType","status","condition","sortBy","minPrice","maxPrice","hideSoldOut","page","specFilters"] as const;const DEFAULT_EXPLORE_QUERY_STATE:ExploreQueryState={search:"",university:"",category:"",subcategory:"",itemType:"",status:"",condition:"",sortBy:"newest",minPrice:"",maxPrice:"",hideSoldOut:false,page:1,specFilters:{}};const parsePositiveIntegerParam=(v:string|null,f:number)=>{if(!v)return f;const n=Number(v);return Number.isInteger(n)&&n>=1?n:f};const parseBooleanParam=(v:string|null)=>v==="1"||v==="true";const parseSpecFiltersParam=(v:string|null)=>{if(!v)return{};try{const p=JSON.parse(v);return p&&typeof p==="object"&&!Array.isArray(p)?p as Record<string,string|string[]|boolean>:{};}catch{return{}}};
export const getExploreStateFromLocation=(location:Pick<Location,"search">):ExploreQueryState=>{const p=new URLSearchParams(location.search);return{search:p.get("search")||"",university:p.get("university")||"",category:p.get("category")||"",subcategory:p.get("subcategory")||"",itemType:p.get("itemType")||"",status:p.get("status")||"",condition:p.get("condition")||"",sortBy:p.get("sortBy")||"newest",minPrice:p.get("minPrice")||"",maxPrice:p.get("maxPrice")||"",hideSoldOut:parseBooleanParam(p.get("hideSoldOut")),page:parsePositiveIntegerParam(p.get("page"),1),specFilters:parseSpecFiltersParam(p.get("specFilters"))};};
export const getMarketChipFromPath=(pathname:string):HeaderChip=>{if(pathname===MARKET_CHIP_PATHS.Deals)return"Deals";if(pathname===MARKET_CHIP_PATHS["Lay-by"])return"Lay-by";if(pathname===MARKET_CHIP_PATHS.Events)return"Events";if(pathname===MARKET_CHIP_PATHS.Wholesale)return"Wholesale";if(pathname===MARKET_CHIP_PATHS.Sellers)return"Sellers";if(pathname===MARKET_CHIP_PATHS.Innovation)return"Innovation";if(pathname===MARKET_CHIP_PATHS.Accommodation)return"Accommodation";if(pathname===MARKET_CHIP_PATHS.Lending)return"Lending";return"All"};export const getMarketChipFromLocation=(l:Pick<Location,"pathname">)=>getMarketChipFromPath(l.pathname);export const getMarketPathFromLocation=(p:string)=>p===EXPLORE_PATH||p.startsWith(`${EXPLORE_PATH}/`)?p:EXPLORE_PATH;
export const writeExploreStateToUrl=(url:URL,state:Partial<ExploreQueryState>)=>{EXPLORE_QUERY_KEYS.forEach(k=>url.searchParams.delete(k));if(state.search)url.searchParams.set("search",state.search);if(state.university)url.searchParams.set("university",state.university);if(state.category)url.searchParams.set("category",state.category);if(state.subcategory)url.searchParams.set("subcategory",state.subcategory);if(state.itemType)url.searchParams.set("itemType",state.itemType);if(state.status)url.searchParams.set("status",state.status);if(state.condition)url.searchParams.set("condition",state.condition);if(state.sortBy&&state.sortBy!=="newest")url.searchParams.set("sortBy",state.sortBy);if(state.minPrice)url.searchParams.set("minPrice",state.minPrice);if(state.maxPrice)url.searchParams.set("maxPrice",state.maxPrice);if(state.hideSoldOut)url.searchParams.set("hideSoldOut","1");if(state.page&&state.page>1)url.searchParams.set("page",String(state.page));if(state.specFilters&&Object.keys(state.specFilters).length)url.searchParams.set("specFilters",JSON.stringify(state.specFilters));};
const pushUrl=(url:URL,replace=false)=>{if(replace)window.history.replaceState({__buymesho:true},"",url.toString());else window.history.pushState({__buymesho:true},"",url.toString());window.dispatchEvent(new PopStateEvent("popstate"));window.scrollTo({top:0,behavior:"smooth"})};const syncExploreStateInUrl=(state:Partial<ExploreQueryState>,mode:"replace"|"push"="replace")=>{const u=new URL(window.location.href);u.pathname=getMarketPathFromLocation(window.location.pathname);u.searchParams.delete("listing");u.searchParams.delete("image");u.searchParams.delete("uid");u.searchParams.delete("id");writeExploreStateToUrl(u,state);pushUrl(u,mode==="replace")};export const replaceExploreStateInUrl=(s:Partial<ExploreQueryState>)=>syncExploreStateInUrl(s,"replace");export const pushExploreStateInUrl=(s:Partial<ExploreQueryState>)=>syncExploreStateInUrl(s,"push");
export const navigateToMarketChip=(chip:HeaderChip)=>{if(typeof window==="undefined")return;const p=MARKET_CHIP_PATHS[chip];if(!p)return;const t=new URL(p,window.location.origin),u=new URL(window.location.href);u.pathname=t.pathname;u.search=t.search;u.searchParams.delete("listing");u.searchParams.delete("image");u.searchParams.delete("uid");u.searchParams.delete("id");pushUrl(u)};export const navigateToExploreWithCategory=(category:string)=>{if(typeof window==="undefined")return;const u=new URL(window.location.href);u.pathname="/category";u.searchParams.set("category",category);u.searchParams.delete("listing");u.searchParams.delete("image");u.searchParams.delete("uid");u.searchParams.delete("id");pushUrl(u)};
export const getAppRouteFromLocation=(location:Pick<Location,"pathname"|"search">):AppRoute=>{const p=new URLSearchParams(location.search);const x=location.pathname;if(x===MESSAGES_PATH)return"messages";if(x===LISTING_PATH&&p.has("listing"))return"listing_details";if(x===EDIT_PATH&&p.has("id"))return"edit";if(x==="/category"&&p.has("category"))return"category";if(x===CREATE_PATH)return"create";if(x===LOGIN_PATH)return"login";if(x===SIGNUP_PATH)return"signup";if(x===FORGOT_PASSWORD_PATH)return"forgot_password";if(x===PROFILE_PATH)return"profile";if(x===VERIFY_EMAIL_PATH)return"verify_email";if(x===ACCOUNT_SETUP_PATH)return"account_setup";if(x===EDIT_PROFILE_PATH)return"edit_profile";if(x===EDIT_ACCOUNT_PATH)return"edit_account";if(x===BECOME_SELLER_PATH)return"become_seller";if(x===CHANGE_PASSWORD_PATH)return"change_password";if(x===CHANGE_EMAIL_PATH)return"change_email";if(x===EMAIL_ACTION_PATH)return"email_action";if(x===MY_LISTINGS_PATH)return"my_listings";if(x===SELLER_ORDERS_PATH)return"seller_orders";if(x===SELLER_PAYOUTS_PATH)return"seller_payouts";if(x===SELLER_DASHBOARD_PATH)return"seller_dashboard";if(x===EVENTS_DASHBOARD_PATH)return"event_creator_overview";if(x===TICKETS_PATH)return"tickets";if(x===ADMIN_PATH)return"admin";if(x===ADMIN_MESSAGES_PATH)return"admin_messages";if(x===ADMIN_EVENTS_PATH)return"admin_events";if(x===ADMIN_PAYMENTS_PATH)return"admin_payments";if(x===ADMIN_TRANSACTION_INSPECTOR_PATH)return"admin_transaction_inspector";if(x===ADMIN_PAYOUTS_PATH)return"admin_payouts";if(x===ADMIN_REPORTS_PATH)return"admin_reports";if(x===ADMIN_SELLER_APPLICATIONS_PATH)return"admin_seller_applications";if(x===ADMIN_MODERATION_QUEUE_PATH)return"admin_moderation_queue";if(x===ADMIN_AUDIT_PATH)return"admin_audit";if(x===ADMIN_SETUP_PATH)return"admin_setup";if(x===ADMIN_BALANCE_PATH)return"admin_balance";if(x===ADMIN_PAYOUT_DESTINATIONS_PATH)return"admin_payout_destinations";if(x===ADMIN_DISPUTES_PATH)return"admin_disputes";if(x===PAYMENT_RETURN_PATH)return"payment_return";if(x===SELLER_PATH&&p.has("uid"))return"seller";if(x===ABOUT_PATH)return"about";if(x===PRIVACY_PATH)return"privacy";if(x===TERMS_PATH)return"terms";if(x===SAFETY_PATH)return"safety";if(x===REPORT_PATH)return"report";if(x===SETTINGS_PATH)return"settings";if(x===SAVED_PATH)return"saved";if(x===HIDDEN_PATH)return"hidden";if(x===EXPLORE_PATH||x.startsWith(`${EXPLORE_PATH}/`))return"explore";return"home"};