import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { postgresDb } from "../../db.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function resolveSchemaPath(): string {
  const candidates = [
    path.join(process.cwd(), "server", "schema.sql"),
    path.join(process.cwd(), "schema.sql"),
    path.join(__dirname, "../../schema.sql"),
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }

  throw new Error(`Could not locate schema.sql. Tried: ${candidates.join(", ")}`);
}

function normalizeSchemaSql(sql: string): string {
  return sql
    .replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/\bAUTOINCREMENT\b/gi, "GENERATED BY DEFAULT AS IDENTITY")
    .replace(/\bDATETIME\b/gi, "TIMESTAMPTZ");
}

export function runMigrations() {
  const schemaPath = resolveSchemaPath();
  const sql = normalizeSchemaSql(fs.readFileSync(schemaPath, "utf8"));

  try {
    postgresDb.exec(sql);
    postgresDb.exec(`ALTER TABLE listings ADD COLUMN IF NOT EXISTS pack_size INTEGER;`);
    postgresDb.exec(`ALTER TABLE listings ADD COLUMN IF NOT EXISTS bulk_units TEXT;`);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.warn(`Migration step skipped because the schema could not be applied safely: ${message}`);
  }

  return postgresDb;
}
