import { MessageChannel, Worker, isMainThread, receiveMessageOnPort, workerData, type MessagePort } from "node:worker_threads";
import dotenv from "dotenv";
import { type PoolClient, type QueryResultRow, Pool } from "pg";

import { closePool, getClient, pool, query, withTransaction } from "./postgres.js";

dotenv.config();

export interface PgCompatQueryResult<Row = Record<string, unknown>> {
  rows: Row[];
  rowCount?: number;
}

export interface PgCompatClient {
  query(text: string, params?: unknown[]): Promise<PgCompatQueryResult>;
  release(): void;
}

export interface PgCompatPreparedStatement {
  run(...params: unknown[]): { changes: number; lastInsertRowid?: number };
  get(...params: unknown[]): Record<string, unknown> | undefined;
  all(...params: unknown[]): Record<string, unknown>[];
}

type WorkerRequest = {
  id: number;
  sql: string;
  params: unknown[];
  signal: SharedArrayBuffer;
};

type WorkerResponse =
  | { id: number; ok: true; rows: Record<string, unknown>[]; rowCount: number }
  | { id: number; ok: false; error: string };

function parseBoolean(value: string | undefined): boolean | undefined {
  if (value === undefined) return undefined;
  const normalized = value.trim().toLowerCase();
  if (["1", "true", "yes", "on"].includes(normalized)) return true;
  if (["0", "false", "no", "off"].includes(normalized)) return false;
  return undefined;
}

function createPgPool() {
  const connectionString = process.env.DATABASE_URL?.trim();
  if (!connectionString) {
    throw new Error("DATABASE_URL is missing");
  }

  const sslMode = process.env.PGSSLMODE?.trim().toLowerCase();
  const sslEnabled = sslMode !== "disable";
  const sslRejectUnauthorized = parseBoolean(process.env.PGSSL_REJECT_UNAUTHORIZED) ?? false;

  return new Pool({
    connectionString,
    ssl: sslEnabled
      ? {
          rejectUnauthorized: sslRejectUnauthorized,
        }
      : false,
    max: Number(process.env.PGPOOL_MAX ?? 10) || 10,
    idleTimeoutMillis: Number(process.env.PGPOOL_IDLE_TIMEOUT_MS ?? 30_000) || 30_000,
    connectionTimeoutMillis: Number(process.env.PGPOOL_CONNECTION_TIMEOUT_MS ?? 10_000) || 10_000,
  });
}

function startWorker(port: MessagePort) {
  const workerPool = createPgPool();

  port.on("message", async (request: WorkerRequest) => {
    const signal = new Int32Array(request.signal);

    try {
      const result = await workerPool.query(request.sql, request.params ?? []);
      const response: WorkerResponse = {
        id: request.id,
        ok: true,
        rows: result.rows ?? [],
        rowCount: result.rowCount ?? (result.rows ?? []).length,
      };
      port.postMessage(response);
    } catch (error) {
      const response: WorkerResponse = {
        id: request.id,
        ok: false,
        error: error instanceof Error ? error.message : String(error),
      };
      port.postMessage(response);
    } finally {
      Atomics.store(signal, 0, 1);
      Atomics.notify(signal, 0, 1);
    }
  });

  port.start();
}

const workerConfig = workerData as { role?: string; port?: MessagePort } | undefined;
if (!isMainThread && workerConfig?.role === "pg-worker" && workerConfig.port) {
  startWorker(workerConfig.port);
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function normalizeParams(sql: string, params: unknown[]): { sql: string; params: unknown[] } {
  const positional = params.length > 1 || (params.length === 1 && !isPlainObject(params[0]));

  if (positional) {
    let index = 0;
    const translated = sql.replace(/\?/g, () => `$${++index}`);
    return { sql: translated, params };
  }

  const paramObject = (params[0] ?? {}) as Record<string, unknown>;
  const seen = new Map<string, number>();
  const ordered: unknown[] = [];

  const translated = sql.replace(/[@:$]([A-Za-z_][A-Za-z0-9_]*)/g, (_match, name: string) => {
    const existing = seen.get(name);
    if (existing) return `$${existing}`;
    const nextIndex = ordered.length + 1;
    seen.set(name, nextIndex);
    ordered.push(paramObject[name]);
    return `$${nextIndex}`;
  });

  return { sql: translated, params: ordered };
}

function buildReturningSql(sql: string): string {
  const trimmed = sql.trim();
  if (!/^insert\b/i.test(trimmed) || /\breturning\b/i.test(trimmed)) return sql;
  const semicolon = trimmed.endsWith(";") ? ";" : "";
  const withoutSemicolon = semicolon ? trimmed.slice(0, -1) : trimmed;
  return `${withoutSemicolon} RETURNING *${semicolon}`;
}

function normalizeSchemaSql(sql: string): string {
  return sql
    .replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace(/\bAUTOINCREMENT\b/gi, "GENERATED BY DEFAULT AS IDENTITY")
    .replace(/\bDATETIME\b/gi, "TIMESTAMPTZ");
}

function fetchTableColumns(tableName: string): Record<string, unknown>[] {
  const result = executeSync(
    `
      SELECT
        column_name AS name,
        data_type AS type,
        is_nullable AS notnull,
        column_default AS dflt_value,
        ordinal_position AS cid
      FROM information_schema.columns
      WHERE table_schema = current_schema()
        AND table_name = $1
      ORDER BY ordinal_position ASC
    `,
    [tableName],
  );

  return result.rows;
}

let worker: Worker | null = null;
let workerPort: MessagePort | null = null;
let requestCounter = 0;

function ensureWorker() {
  if (worker && workerPort) return;

  const { port1, port2 } = new MessageChannel();
  workerPort = port1;
  worker = new Worker(new URL(import.meta.url), {
    type: "module",
    workerData: { role: "pg-worker", port: port2 },
    transferList: [port2],
  } as any);

  worker.on("error", (error) => {
    console.warn("PostgreSQL worker error:", error);
  });

  worker.on("exit", (code) => {
    if (code !== 0) {
      console.warn(`PostgreSQL worker exited with code ${code}`);
    }
  });

  worker.unref();
  workerPort.unref?.();
}

function executeSync(sql: string, params: unknown[] = []): { rows: Record<string, unknown>[]; rowCount: number } {
  ensureWorker();
  if (!workerPort) {
    throw new Error("PostgreSQL worker is not available");
  }

  const payload = { id: ++requestCounter, sql, params, signal: new SharedArrayBuffer(4) } satisfies WorkerRequest;
  const signal = new Int32Array(payload.signal);
  workerPort.postMessage(payload);

  const timeoutMs = Number(process.env.PG_SYNC_QUERY_TIMEOUT_MS ?? 30_000) || 30_000;
  const waitResult = Atomics.wait(signal, 0, 0, timeoutMs);
  if (waitResult === "timed-out") {
    throw new Error(`PostgreSQL query timed out after ${timeoutMs}ms`);
  }

  const packet = receiveMessageOnPort(workerPort);
  if (!packet || !packet.message) {
    throw new Error("PostgreSQL worker returned no response");
  }

  const response = packet.message as WorkerResponse;
  if (response.id !== payload.id) {
    throw new Error("PostgreSQL worker response mismatch");
  }

  if (!response.ok) {
    throw new Error(`PostgreSQL query failed: ${response.error}`);
  }

  return {
    rows: Array.isArray(response.rows) ? response.rows : [],
    rowCount: Number.isFinite(response.rowCount) ? Number(response.rowCount) : 0,
  };
}

export class PgCompatDatabase {
  prepare(sql: string): PgCompatPreparedStatement {
    return {
      run: (...params: unknown[]) => {
        const normalized = normalizeParams(buildReturningSql(normalizeSchemaSql(sql)), params);
        const result = executeSync(normalized.sql, normalized.params);
        const firstRow = result.rows[0] as Record<string, unknown> | undefined;
        const lastInsertRowid = firstRow?.id !== undefined ? Number(firstRow.id) : undefined;
        return { changes: result.rowCount, ...(Number.isFinite(lastInsertRowid) ? { lastInsertRowid } : {}) };
      },
      get: (...params: unknown[]) => {
        const normalized = normalizeParams(normalizeSchemaSql(sql), params);
        const result = executeSync(normalized.sql, normalized.params);
        return (result.rows[0] as Record<string, unknown> | undefined) ?? undefined;
      },
      all: (...params: unknown[]) => {
        const normalized = normalizeParams(normalizeSchemaSql(sql), params);
        const result = executeSync(normalized.sql, normalized.params);
        return result.rows;
      },
    };
  }

  exec(sql: string): void {
    if (!sql.trim()) return;
    executeSync(normalizeSchemaSql(sql), []);
  }

  pragma(_statement: string): void {}
  transaction<T extends (...args: any[]) => any>(fn: T): T {
    return ((...args: any[]) => fn(...args)) as T;
  }
  close(): void {
    void closePool();
  }
}

export const postgresDb = new PgCompatDatabase();
export function getPaymentDb() {
  return postgresDb;
}
export async function getDatabaseClient(): Promise<PoolClient> {
  return getClient();
}
export { pool, query, closePool, getClient, withTransaction };
export type { QueryResultRow };
