import type { ServicePaymentRecord } from "../services/service-payment.repository.js";

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function formatMoney(amount: number, currency: string): string {
  return `${currency} ${new Intl.NumberFormat("en-MW", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(amount)}`;
}

function formatDate(value: string | null): string {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleString("en-MW", {
    dateStyle: "medium",
    timeStyle: "short",
  });
}

function serviceLabel(type: ServicePaymentRecord["serviceType"]): string {
  if (type === "graphic_design") return "Graphic Design";
  if (type === "website_development") return "Website Development";
  return "Graphic Design + Web Development";
}

function paymentModeLabel(mode: ServicePaymentRecord["paymentMode"]): string {
  if (mode === "deposit") return "50% Deposit";
  if (mode === "balance") return "Final Balance";
  if (mode === "full") return "Full Payment";
  return "-";
}

export function renderXhovileStudioPaymentSuccessEmail(
  payment: ServicePaymentRecord,
): { text: string; html: string } {
  const customerName = escapeHtml(payment.customerName);
  const customerPhone = escapeHtml(payment.customerPhone);
  const customerEmail = escapeHtml(payment.customerEmail ?? "Not provided");
  const service = escapeHtml(serviceLabel(payment.serviceType));
  const description = escapeHtml(payment.description);
  const mode = escapeHtml(paymentModeLabel(payment.paymentMode));
  const reference = escapeHtml(payment.paymentReference ?? payment.id);
  const providerReference = escapeHtml(payment.providerReference ?? "Not provided");
  const amount = escapeHtml(formatMoney(payment.amount, payment.currency));
  const projectTotal =
    payment.projectTotal === null
      ? "Not provided"
      : escapeHtml(formatMoney(payment.projectTotal, payment.currency));
  const projectReference = escapeHtml(payment.projectReference ?? "Not provided");
  const paidAt = escapeHtml(formatDate(payment.paidAt));

  const text = [
    "XHOVILÉ STUDIO — Successful Payment",
    "",
    "A Studio payment has been successfully verified.",
    "",
    `Customer: ${payment.customerName}`,
    `Phone: ${payment.customerPhone}`,
    `Email: ${payment.customerEmail ?? "Not provided"}`,
    `Service: ${serviceLabel(payment.serviceType)}`,
    `Payment mode: ${paymentModeLabel(payment.paymentMode)}`,
    `Amount paid: ${formatMoney(payment.amount, payment.currency)}`,
    `Project total: ${payment.projectTotal === null ? "Not provided" : formatMoney(payment.projectTotal, payment.currency)}`,
    `Project reference: ${payment.projectReference ?? "Not provided"}`,
    `Payment reference: ${payment.paymentReference ?? payment.id}`,
    `PayChangu reference: ${payment.providerReference ?? "Not provided"}`,
    `Paid at: ${formatDate(payment.paidAt)}`,
    `Description: ${payment.description}`,
    "",
    "This notification was generated by the Xhovilé Studio payment system.",
  ].join("\n");

  const html = `<!doctype html>
<html>
  <body style="margin:0;background:#f6f1ea;font-family:Arial,Helvetica,sans-serif;color:#171717;">
    <div style="max-width:640px;margin:32px auto;padding:0 16px;">
      <div style="background:#ffffff;border:1px solid #e5ded6;border-radius:18px;overflow:hidden;">
        <div style="height:5px;background:#8f1528;"></div>
        <div style="padding:28px 28px 22px;">
          <div style="font-size:22px;font-weight:800;letter-spacing:.08em;color:#8f1528;">XHOVILÉ STUDIO</div>
          <div style="margin-top:6px;font-size:12px;font-weight:700;letter-spacing:.12em;color:#777;text-transform:uppercase;">Successful Payment</div>
        </div>
        <div style="padding:0 28px 28px;">
          <div style="padding:16px;border-radius:14px;background:#f8f4ef;border:1px solid #e8e0d7;">
            <div style="font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#777;">Amount paid</div>
            <div style="margin-top:6px;font-size:28px;font-weight:800;color:#8f1528;">${amount}</div>
          </div>

          <table style="width:100%;margin-top:20px;border-collapse:collapse;font-size:14px;">
            <tr><td style="padding:8px 0;color:#777;">Customer</td><td style="padding:8px 0;text-align:right;font-weight:700;">${customerName}</td></tr>
            <tr><td style="padding:8px 0;color:#777;">Phone</td><td style="padding:8px 0;text-align:right;font-weight:700;">${customerPhone}</td></tr>
            <tr><td style="padding:8px 0;color:#777;">Email</td><td style="padding:8px 0;text-align:right;font-weight:700;">${customerEmail}</td></tr>
            <tr><td style="padding:8px 0;color:#777;">Service</td><td style="padding:8px 0;text-align:right;font-weight:700;">${service}</td></tr>
            <tr><td style="padding:8px 0;color:#777;">Payment mode</td><td style="padding:8px 0;text-align:right;font-weight:700;">${mode}</td></tr>
            <tr><td style="padding:8px 0;color:#777;">Project total</td><td style="padding:8px 0;text-align:right;font-weight:700;">${projectTotal}</td></tr>
            <tr><td style="padding:8px 0;color:#777;">Project reference</td><td style="padding:8px 0;text-align:right;font-weight:700;">${projectReference}</td></tr>
            <tr><td style="padding:8px 0;color:#777;">Payment reference</td><td style="padding:8px 0;text-align:right;font-weight:700;">${reference}</td></tr>
            <tr><td style="padding:8px 0;color:#777;">PayChangu reference</td><td style="padding:8px 0;text-align:right;font-weight:700;">${providerReference}</td></tr>
            <tr><td style="padding:8px 0;color:#777;">Paid at</td><td style="padding:8px 0;text-align:right;font-weight:700;">${paidAt}</td></tr>
          </table>

          <div style="margin-top:18px;padding-top:18px;border-top:1px solid #eee;">
            <div style="font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#777;">Description</div>
            <div style="margin-top:7px;font-size:14px;line-height:1.6;">${description}</div>
          </div>

          <div style="margin-top:24px;font-size:11px;line-height:1.6;color:#777;">
            This notification was generated by the Xhovilé Studio payment system.
          </div>
        </div>
      </div>
    </div>
  </body>
</html>`;

  return { text, html };
}
