import assert from "node:assert/strict";
import test from "node:test";
import { notifyTicketDelivery, notifyTicketPurchaseConfirmation } from "../event-ticket.notification.js";
import { notifyPayoutCompleted } from "../payout-completed.notification.js";

const ticket = { email:"buyer@example.com", buyerName:"Ada Buyer", eventName:"Campus Concert", ticketType:"VIP", quantity:2, orderReference:"ord-event-1", amount:5000, currency:"MWK", eventDate:"2026-10-01", startTime:"18:00", venue:"Main Hall", location:"Campus", ticketId:"ticket-1", accessUrl:"https://buymesho.app/orders/ord-event-1", orderStatus:"paid" };
test("ticket purchase confirmation sends only for a successful order with authoritative ticket details", async()=>{const messages:any[]=[];const sent=await notifyTicketPurchaseConfirmation(ticket,{send:async message=>{messages.push(message);return{messageId:"1"};}});assert.equal(sent,true);assert.equal(messages[0].sender,"transactional");assert.deepEqual(messages[0].to,{email:"buyer@example.com",name:"Ada Buyer"});assert.equal(messages[0].subject,"Your BuyMesho ticket purchase is confirmed");assert.match(messages[0].text,/Campus Concert/);assert.match(messages[0].text,/ord-event-1/);assert.equal(await notifyTicketPurchaseConfirmation({...ticket,orderStatus:"pending_payment"},{send:async()=>{throw new Error("must not send");}}),false);});
test("issued ticket delivery includes its identifier and will not send before the order is successful",async()=>{const messages:any[]=[];assert.equal(await notifyTicketDelivery(ticket,{send:async message=>{messages.push(message);return{messageId:"2"};}}),true);assert.equal(messages[0].sender,"transactional");assert.equal(messages[0].subject,"Your BuyMesho event ticket is ready");assert.match(messages[0].text,/ticket-1/);assert.equal(await notifyTicketDelivery({...ticket,orderStatus:"failed"},{send:async()=>{throw new Error("must not send");}}),false);});
test("payout completed email sends only when the authoritative payout status is paid",async()=>{const messages:any[]=[];const input={email:"seller@example.com",sellerName:"Ada's Shop",amount:1250,currency:"MWK",payoutId:"payout-1",orderReference:"ord-1",completedAt:"2026-10-01T12:00:00Z",status:"paid"};assert.equal(await notifyPayoutCompleted(input,{send:async message=>{messages.push(message);return{messageId:"3"};}}),true);assert.equal(messages[0].sender,"transactional");assert.deepEqual(messages[0].to,{email:"seller@example.com",name:"Ada's Shop"});assert.equal(messages[0].subject,"Your BuyMesho payout has been completed");assert.match(messages[0].text,/payout-1/);assert.match(messages[0].text,/1,250.00 MWK/);for(const status of ["pending","processing","failed"]){assert.equal(await notifyPayoutCompleted({...input,status},{send:async()=>{throw new Error("must not send");}}),false);}});
