import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, CheckCircle2, ChevronRight, Package, RefreshCw, Send, ShieldAlert } from "lucide-react";
import { apiFetch } from "./lib/api";
import { navigateToPath } from "./lib/appNavigation";
import { SELLER_HUB_PATH, SELLER_ORDERS_PATH } from "./lib/appNavigation.paths";
import { useAccountProfile } from "./hooks/useAccountProfile";
import { getSellerCache, setSellerCache } from "./lib/sellerWorkspaceCache";

type BuyerDetails = { fullName: string; phone: string; addressLine: string; area: string; townOrDistrict: string; landmark: string } | null;
type DeliveryStatus = "action_required" | "pending_delivery" | "delivered";
type DisputeSummary = { id?: string | null; caseId?: string | null; status?: string | null; state?: string | null; reason?: string | null; requestedResolution?: string | null; outcome?: string | null; windowEndsAt?: string | null; openedAt?: string | null; latestAttempt?: { id?: string | null; status?: string | null; reason?: string | null; requestedResolution?: string | null } | null };
type RefundRequestSummary = { id?: string | null; status?: string | null; requestType?: string | null; amountRequested?: number; requestedResolution?: string | null; windowEndsAt?: string | null };
type OrderBundle = { order: { id: string; status: string; deliveryStatus?: DeliveryStatus; currency: string; subtotal: { amount: number; currency: string }; total: { amount: number; currency: string }; paymentReference?: string | null; settlementRoute?: string | null; items: Array<{ title: string; quantity: number; unitPrice: { amount: number; currency: string } }>; buyerDetails?: BuyerDetails; placedAt?: string | null; paidAt?: string | null; fulfilledAt?: string | null; createdAt: string; updatedAt: string }; payment: { status?: string | null; verified?: boolean; reference?: string } | null; escrow: { state?: string | null } | null; payoutStatus?: string | null; dispute: DisputeSummary | null; refundRequest?: RefundRequestSummary | null };
type FilterKey = "all" | "action_required" | "escrow" | "delivered" | "pending_delivery" | "disputed";
type DisputedFilter = "all" | "pending" | "settled";
type SellerResolution = "refund" | "replacement" | "rejected" | null;
const FILTERS: Array<{ key: FilterKey; label: string }> = [
  { key: "all", label: "All" }, { key: "action_required", label: "Action Required" }, { key: "escrow", label: "In Escrow" },
  { key: "delivered", label: "Delivered" }, { key: "pending_delivery", label: "Pending Delivery" }, { key: "disputed", label: "Disputed" },
];
function money(order: OrderBundle["order"]): string { return `${order.currency} ${Number(order.total.amount).toLocaleString()}`; }
function normalize(value: unknown): string { return String(value ?? "").trim().toLowerCase(); }
function isSellerOrder(bundle: OrderBundle): boolean { return !["draft", "pending_payment"].includes(normalize(bundle.order.status)); }
function isDelivered(bundle: OrderBundle): boolean { return bundle.order.deliveryStatus === "delivered" || ["fulfilled", "closed"].includes(normalize(bundle.order.status)); }
function isPendingDelivery(bundle: OrderBundle): boolean { return bundle.order.deliveryStatus === "pending_delivery" && !isDelivered(bundle); }
function isSettledDispute(bundle: OrderBundle): boolean {
  const status = normalize(bundle.dispute?.status ?? bundle.dispute?.state);
  const outcome = normalize(bundle.dispute?.outcome);
  const refundStatus = normalize(bundle.refundRequest?.status);
  const orderStatus = normalize(bundle.order.status);
  const escrowState = normalize(bundle.escrow?.state);
  return ["resolved", "closed"].includes(status)
    || ["refunded", "returned", "seller_refund_confirmed", "seller_refund_accepted", "return", "return_and_refund", "seller_replacement_confirmed", "seller_replacement_committed", "seller_rejected", "seller_dispute_rejected"].includes(outcome)
    || ["refunded", "returned", "settled"].includes(refundStatus)
    || ["refunded", "returned"].includes(orderStatus)
    || ["refunded", "returned"].includes(escrowState);
}
function hasDispute(bundle: OrderBundle): boolean { return Boolean(bundle.dispute?.id || bundle.dispute?.caseId || bundle.refundRequest?.id); }
function isPendingDispute(bundle: OrderBundle): boolean {
  if (!hasDispute(bundle) || isSettledDispute(bundle)) return false;
  const disputeStatus = normalize(bundle.dispute?.status ?? bundle.dispute?.state);
  const refundStatus = normalize(bundle.refundRequest?.status);
  return ["open", "under_review", "awaiting_response"].includes(disputeStatus) || ["requested", "under_review", "processing", "approved"].includes(refundStatus);
}
function isActionRequired(bundle: OrderBundle): boolean {
  if (!isSellerOrder(bundle) || isDelivered(bundle) || isPendingDelivery(bundle) || isSettledDispute(bundle)) return false;
  return bundle.order.deliveryStatus !== "delivered";
}
function isEscrow(bundle: OrderBundle): boolean {
  if (isSettledDispute(bundle)) return false;
  return normalize(bundle.escrow?.state) === "in_escrow" || ["paid", "in_escrow"].includes(normalize(bundle.order.status));
}
function settlementLabel(bundle: OrderBundle): "Refunded" | "Returned" | "Replacement" | "Rejected" | "Resolved" {
  const values = [normalize(bundle.dispute?.outcome), normalize(bundle.refundRequest?.status), normalize(bundle.order.status), normalize(bundle.escrow?.state)];
  if (values.some((value) => ["seller_replacement_confirmed", "seller_replacement_committed"].includes(value))) return "Replacement";
  if (values.some((value) => ["seller_rejected", "seller_dispute_rejected"].includes(value))) return "Rejected";
  if (values.some((value) => ["returned", "return"].includes(value))) return "Returned";
  if (values.some((value) => ["refunded", "seller_refund_confirmed", "seller_refund_accepted", "refund", "return_and_refund", "settled"].includes(value))) return "Refunded";
  return "Resolved";
}
function matchesFilter(bundle: OrderBundle, filter: FilterKey, disputedFilter: DisputedFilter): boolean {
  if (!isSellerOrder(bundle)) return false;
  if (filter === "all") return true;
  if (filter === "action_required") return isActionRequired(bundle);
  if (filter === "escrow") return isEscrow(bundle);
  if (filter === "delivered") return isDelivered(bundle);
  if (filter === "pending_delivery") return isPendingDelivery(bundle);
  if (!hasDispute(bundle)) return false;
  if (disputedFilter === "pending") return isPendingDispute(bundle);
  if (disputedFilter === "settled") return isSettledDispute(bundle);
  return true;
}
function getFilterCount(orders: OrderBundle[], filter: FilterKey, disputedFilter: DisputedFilter): number { return orders.filter((bundle) => matchesFilter(bundle, filter, disputedFilter)).length; }
function orderStatusLabel(bundle: OrderBundle): string {
  if (isSettledDispute(bundle)) return `Dispute — ${settlementLabel(bundle)}`;
  if (isPendingDispute(bundle)) return "Dispute Pending";
  if (bundle.order.deliveryStatus === "pending_delivery") return "Pending Delivery";
  if (isDelivered(bundle)) return "Delivered";
  if (isEscrow(bundle)) return "In Escrow";
  if (normalize(bundle.order.status) === "paid") return "Action Required";
  return bundle.order.status.replaceAll("_", " ");
}
function requestedResolutionLabel(value: unknown): string { const normalized = normalize(value); if (normalized === "refund") return "Refund"; if (normalized === "return") return "Return"; if (normalized === "return_and_refund") return "Return + refund"; return "BuyMesho review"; }
export default function SellerOrdersPage() {
  const { profileLoading, profile } = useAccountProfile();
  const cachedOrders = getSellerCache<OrderBundle[]>("orders");
  const [orders, setOrders] = useState<OrderBundle[]>(cachedOrders ?? []);
  const [filter, setFilter] = useState<FilterKey>("all");
  const [disputedFilter, setDisputedFilter] = useState<DisputedFilter>("all");
  const [selected, setSelected] = useState<OrderBundle | null>(null);
  const [loading, setLoading] = useState(cachedOrders === null);
  const [refreshing, setRefreshing] = useState(false);
  const [actionLoading, setActionLoading] = useState(false);
  const [resolutionLoading, setResolutionLoading] = useState(false);
  const [sellerResolution, setSellerResolution] = useState<SellerResolution>(null);
  const [resolutionReason, setResolutionReason] = useState("");
  const [refundAmount, setRefundAmount] = useState("");
  const [refundMethod, setRefundMethod] = useState("mobile_money");
  const [refundTransactionId, setRefundTransactionId] = useState("");
  const [refundDate, setRefundDate] = useState(() => new Date().toISOString().slice(0, 10));
  const [refundDestination, setRefundDestination] = useState("");
  const [refundNote, setRefundNote] = useState("");
  const [refundEvidence, setRefundEvidence] = useState<string[]>([]);
  const [refundEvidenceInput, setRefundEvidenceInput] = useState("");
  const [error, setError] = useState<string | null>(null);

  const loadOrders = async (force = false) => {
    if (!force) { const cached = getSellerCache<OrderBundle[]>("orders"); if (cached !== null) { setOrders(cached); setLoading(false); return; } }
    if (force) setRefreshing(true); else setLoading(true);
    try { const data = await apiFetch("/api/seller/orders"); const next = Array.isArray(data) ? data as OrderBundle[] : []; setOrders(next); setSellerCache("orders", next); setError(null); }
    catch (err) { setError(err instanceof Error ? err.message : "Failed to load seller orders"); }
    finally { setLoading(false); setRefreshing(false); }
  };
  useEffect(() => { if (!profileLoading && profile?.is_seller && cachedOrders === null) void loadOrders(); }, [profileLoading, profile?.is_seller]);
  const selectedOrderId = new URLSearchParams(window.location.search).get("order");
  useEffect(() => { if (!selectedOrderId) { setSelected(null); return; } setSelected(orders.find((entry) => entry.order.id === selectedOrderId) ?? null); }, [orders, selectedOrderId]);
  useEffect(() => { setSellerResolution(null); setResolutionReason(""); }, [selectedOrderId]);
  const filteredOrders = useMemo(() => orders.filter((bundle) => matchesFilter(bundle, filter, disputedFilter)), [orders, filter, disputedFilter]);
  const pendingDisputes = useMemo(() => orders.filter(isPendingDispute), [orders]);
  const settledDisputes = useMemo(() => orders.filter((bundle) => hasDispute(bundle) && isSettledDispute(bundle)), [orders]);
  if (profileLoading) return <main className="min-h-screen grid place-items-center bg-zinc-50 text-sm font-semibold text-zinc-500">Loading seller orders…</main>;
  if (!profile?.is_seller) return <main className="min-h-screen grid place-items-center bg-zinc-50 px-6 text-center"><div><p className="font-extrabold text-zinc-900">Seller access required</p><button type="button" onClick={() => navigateToPath(SELLER_HUB_PATH)} className="mt-3 text-sm font-bold text-zinc-600 hover:text-zinc-950">Back to Workspace</button></div></main>;
  const openOrder = (bundle: OrderBundle) => { setSelected(bundle); navigateToPath(`${SELLER_ORDERS_PATH}&order=${encodeURIComponent(bundle.order.id)}`); };
  const closeOrder = () => { setSelected(null); navigateToPath(SELLER_ORDERS_PATH); };
  const updateSelectedBundle = (nextBundle: OrderBundle) => { setOrders((current) => { const next = current.map((entry) => entry.order.id === nextBundle.order.id ? nextBundle : entry); setSellerCache("orders", next); return next; }); setSelected(nextBundle); };
  const markAsPendingDelivery = async (bundle: OrderBundle) => { try { setActionLoading(true); const updated = await apiFetch(`/api/seller/orders/${encodeURIComponent(bundle.order.id)}/mark-pending-delivery`, { method: "POST" }); updateSelectedBundle(updated as OrderBundle); } catch (err) { setError(err instanceof Error ? err.message : "Failed to update delivery status"); } finally { setActionLoading(false); } };
  const contactBuyer = async (bundle: OrderBundle) => { try { setResolutionLoading(true); setError(null); const result = await apiFetch(`/api/seller/disputes/${encodeURIComponent(bundle.order.id)}/dispute/contact-buyer`, { method: "POST" }); if (result?.conversationTarget) { navigateToPath(String(result.conversationTarget)); return; } setError("Buyer conversation could not be opened."); } catch (err) { setError(err instanceof Error ? err.message : "Failed to open buyer conversation"); } finally { setResolutionLoading(false); } };
  const resetResolutionFields = () => { setSellerResolution(null); setResolutionReason(""); setRefundAmount(""); setRefundTransactionId(""); setRefundDestination(""); setRefundNote(""); setRefundEvidence([]); setRefundEvidenceInput(""); setRefundDate(new Date().toISOString().slice(0, 10)); setError(null); };
  const payoutPaid = normalize(selected?.payoutStatus) === "paid";
  const chooseSellerResolution = (resolution: Exclude<SellerResolution, null>) => { setSellerResolution(resolution); setResolutionReason(""); setError(null); };
  const addEvidence = () => { const value = refundEvidenceInput.trim(); if (!value || refundEvidence.includes(value)) return setRefundEvidenceInput(""); setRefundEvidence((current) => [...current, value].slice(0, 20)); setRefundEvidenceInput(""); };
  const submitSellerRefund = async () => { if (!selected) return; const amount = Number(refundAmount); if (!Number.isFinite(amount) || amount <= 0) return setError("Enter a valid refund amount."); if (amount > Number(selected.order.total.amount)) return setError("Refund amount cannot exceed the order total."); if (!payoutPaid) return setError("Seller payout must be paid before recording a seller refund."); if (!refundTransactionId.trim()) return setError("Transaction ID is required."); if (!refundDate) return setError("Refund date is required."); try { setResolutionLoading(true); setError(null); await apiFetch(`/api/seller/disputes/${encodeURIComponent(selected.order.id)}/dispute/confirm-refunded`, { method: "POST", body: JSON.stringify({ amount, refundMethod, transactionId: refundTransactionId.trim(), refundDate, destination: refundDestination.trim() || undefined, note: refundNote.trim() || undefined, evidence: refundEvidence }) }); resetResolutionFields(); await loadOrders(true); } catch (err) { setError(err instanceof Error ? err.message : "Failed to record seller refund"); } finally { setResolutionLoading(false); } };
  const submitSellerNonRefund = async () => { if (!selected || (sellerResolution !== "replacement" && sellerResolution !== "rejected")) return; const explanation = resolutionReason.trim(); if (explanation.length < 10) return setError("Please provide at least 10 characters explaining this resolution."); try { setResolutionLoading(true); setError(null); await apiFetch(`/api/seller/disputes/${encodeURIComponent(selected.order.id)}/dispute/resolve`, { method: "POST", body: JSON.stringify({ resolution: sellerResolution, reason: explanation, paymentStatus: normalize(selected.order.status) }) }); resetResolutionFields(); await loadOrders(true); } catch (err) { setError(err instanceof Error ? err.message : "Failed to submit seller resolution"); } finally { setResolutionLoading(false); } };
  if (selected) {
    const buyer = selected.order.buyerDetails; const dispute = selected.dispute; const disputeReason = String(dispute?.reason ?? dispute?.latestAttempt?.reason ?? "").trim(); const selectedResolution = dispute?.requestedResolution ?? dispute?.latestAttempt?.requestedResolution ?? selected.refundRequest?.requestedResolution; const settled = isSettledDispute(selected); const pending = isPendingDispute(selected); const settledLabel = settlementLabel(selected); const paidOrder = normalize(selected.order.status) === "paid";
    return <main className="min-h-screen bg-zinc-50 px-4 py-6 md:px-8"><div className="mx-auto max-w-4xl"><button type="button" onClick={closeOrder} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-zinc-600 hover:text-zinc-950"><ArrowLeft className="h-4 w-4" /> Back to Seller Orders</button><section className="rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-zinc-400">Order</p><h1 className="mt-1 text-2xl font-black text-zinc-950">{selected.order.id}</h1></div><span className={`rounded-full px-3 py-1.5 text-xs font-extrabold ${settled ? "bg-emerald-100 text-emerald-900" : pending ? "bg-amber-100 text-amber-900" : "bg-zinc-100 text-zinc-800"}`}>{orderStatusLabel(selected)}</span></div>
      {hasDispute(selected) ? <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-start gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-700" /><div className="min-w-0 flex-1"><p className="text-sm font-black text-amber-950">{settled ? `Dispute settled — ${settledLabel}` : pending ? "Buyer has an open dispute" : "Dispute history"}</p><p className="mt-1 text-sm leading-6 text-amber-900/80">{settled ? "This dispute is settled and no further seller resolution is required." : pending ? "Review the buyer’s request and choose one resolution." : "This order has dispute history."}</p>{disputeReason ? <div className="mt-3 rounded-xl border border-amber-200 bg-white p-4"><p className="text-[10px] font-black uppercase tracking-[0.16em] text-amber-700">Issue</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-zinc-800">{disputeReason}</p></div> : null}</div></div></div> : null}
      <div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-zinc-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-zinc-400">Purchase</p>{selected.order.items.map((item) => <div key={`${item.title}-${item.quantity}`} className="mt-3 flex justify-between gap-4 text-sm"><span className="font-semibold text-zinc-700">{item.title} × {item.quantity}</span><span className="font-extrabold text-zinc-950">{selected.order.currency} {Number(item.unitPrice.amount * item.quantity).toLocaleString()}</span></div>)}<div className="mt-4 flex justify-between border-t border-zinc-200 pt-3 font-black"><span>Total</span><span>{money(selected.order)}</span></div></div><div className="rounded-2xl bg-zinc-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-zinc-400">Buyer & Delivery</p>{buyer ? <div className="mt-3 space-y-1 text-sm text-zinc-700"><p className="font-extrabold text-zinc-950">{buyer.fullName}</p><p>{buyer.phone}</p><p>{buyer.addressLine}</p><p>{buyer.area}, {buyer.townOrDistrict}</p>{buyer.landmark ? <p>Landmark: {buyer.landmark}</p> : null}</div> : <p className="mt-3 text-sm text-zinc-500">Buyer delivery details are not available for this order.</p>}</div></div>
      <div className="mt-4 rounded-2xl border border-zinc-200 p-4"><p className="text-xs font-black uppercase tracking-wider text-zinc-400">Payment, Escrow & Payout</p><div className="mt-3 grid gap-2 text-sm md:grid-cols-3"><p><span className="text-zinc-500">Payment:</span> <strong>{selected.payment?.status ?? "—"}</strong></p><p><span className="text-zinc-500">Escrow:</span> <strong>{selected.escrow?.state ?? "—"}</strong></p><p><span className="text-zinc-500">Seller payout:</span> <strong>{selected.payoutStatus ?? "Not available"}</strong></p></div></div>
      {pending || settled ? <div className={`mt-5 rounded-2xl border p-5 ${settled ? "border-emerald-200 bg-emerald-50" : "border-sky-200 bg-sky-50"}`}><p className={`text-sm font-black ${settled ? "text-emerald-950" : "text-sky-950"}`}>{settled ? `Seller dispute actions closed — ${settledLabel}` : "Seller dispute resolution"}</p>{pending && paidOrder ? <><div className="mt-4 grid gap-2 sm:grid-cols-3"><button type="button" disabled={resolutionLoading} onClick={() => chooseSellerResolution("refund")} className={`rounded-xl border px-4 py-3 text-sm font-extrabold ${sellerResolution === "refund" ? "border-zinc-950 bg-zinc-950 text-white" : "border-zinc-200 bg-white text-zinc-900"}`}>Refund</button><button type="button" disabled={resolutionLoading} onClick={() => chooseSellerResolution("replacement")} className={`rounded-xl border px-4 py-3 text-sm font-extrabold ${sellerResolution === "replacement" ? "border-zinc-950 bg-zinc-950 text-white" : "border-zinc-200 bg-white text-zinc-900"}`}>Send another item</button><button type="button" disabled={resolutionLoading} onClick={() => chooseSellerResolution("rejected")} className={`rounded-xl border px-4 py-3 text-sm font-extrabold ${sellerResolution === "rejected" ? "border-zinc-950 bg-zinc-950 text-white" : "border-zinc-200 bg-white text-zinc-900"}`}>Reject</button></div>
        {sellerResolution === "refund" ? <div className="mt-4 rounded-2xl border border-zinc-200 bg-white p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-zinc-700">Refund amount<input value={refundAmount} onChange={(e) => setRefundAmount(e.target.value)} type="number" min="0" step="0.01" className="mt-1 w-full rounded-xl border border-zinc-200 px-3 py-2.5" /></label><label className="text-sm font-semibold text-zinc-700">Refund method<select value={refundMethod} onChange={(e) => setRefundMethod(e.target.value)} className="mt-1 w-full rounded-xl border border-zinc-200 px-3 py-2.5"><option value="mobile_money">Mobile money</option><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="other">Other</option></select></label><label className="text-sm font-semibold text-zinc-700">Transaction ID<input value={refundTransactionId} onChange={(e) => setRefundTransactionId(e.target.value)} className="mt-1 w-full rounded-xl border border-zinc-200 px-3 py-2.5" /></label><label className="text-sm font-semibold text-zinc-700">Refund date<input value={refundDate} onChange={(e) => setRefundDate(e.target.value)} type="date" className="mt-1 w-full rounded-xl border border-zinc-200 px-3 py-2.5" /></label><label className="text-sm font-semibold text-zinc-700 sm:col-span-2">Refund destination<input value={refundDestination} onChange={(e) => setRefundDestination(e.target.value)} className="mt-1 w-full rounded-xl border border-zinc-200 px-3 py-2.5" placeholder="Optional account/number" /></label><label className="text-sm font-semibold text-zinc-700 sm:col-span-2">Note<textarea value={refundNote} onChange={(e) => setRefundNote(e.target.value)} rows={3} className="mt-1 w-full rounded-xl border border-zinc-200 px-3 py-2.5" /></label></div><div className="mt-3 flex gap-2"><input value={refundEvidenceInput} onChange={(e) => setRefundEvidenceInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); addEvidence(); } }} className="min-w-0 flex-1 rounded-xl border border-zinc-200 px-3 py-2.5 text-sm" placeholder="Evidence reference (optional)" /><button type="button" onClick={addEvidence} className="rounded-xl border border-zinc-200 px-3 py-2 text-xs font-bold">Add</button></div>{refundEvidence.length ? <div className="mt-2 flex flex-wrap gap-2">{refundEvidence.map((item) => <span key={item} className="rounded-full bg-zinc-100 px-3 py-1 text-xs font-semibold text-zinc-600">{item}</span>)}</div> : null}<button type="button" disabled={resolutionLoading || !payoutPaid} onClick={() => void submitSellerRefund()} className="mt-4 w-full rounded-xl bg-zinc-950 px-4 py-3 text-sm font-extrabold text-white disabled:opacity-50 sm:w-auto">{resolutionLoading ? "Submitting…" : "Submit Refund"}</button></div> : null}
        {sellerResolution === "replacement" || sellerResolution === "rejected" ? <div className="mt-4 rounded-2xl border border-zinc-200 bg-white p-4"><p className="text-sm font-black text-zinc-900">{sellerResolution === "replacement" ? "Send another item" : "Reject dispute"}</p><p className="mt-1 text-sm text-zinc-500">{sellerResolution === "replacement" ? "Explain the replacement you will send. Use Contact Buyer to agree the physical delivery details." : "Give the buyer a clear explanation for the rejection."}</p><textarea value={resolutionReason} onChange={(e) => setResolutionReason(e.target.value)} rows={5} className="mt-4 w-full rounded-xl border border-zinc-200 px-3 py-2.5 text-sm" placeholder={sellerResolution === "replacement" ? "Explain the replacement…" : "Explain why you are rejecting this dispute…"} /><button type="button" disabled={resolutionLoading || resolutionReason.trim().length < 10} onClick={() => void submitSellerNonRefund()} className="mt-4 w-full rounded-xl bg-zinc-950 px-4 py-3 text-sm font-extrabold text-white disabled:opacity-50 sm:w-auto">{resolutionLoading ? "Submitting…" : "Submit Resolution"}</button></div> : null}</> : null}<div className="mt-4 flex flex-wrap gap-2"><button type="button" disabled={resolutionLoading} onClick={() => void contactBuyer(selected)} className="inline-flex items-center gap-2 rounded-xl border border-zinc-300 bg-white px-4 py-2.5 text-sm font-extrabold text-zinc-900 disabled:opacity-50"><Send className="h-4 w-4" />Contact Buyer</button></div></div> : null}
      {isActionRequired(selected) ? <div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-sm font-black text-emerald-950">Ready to send</p><p className="mt-1 text-sm text-emerald-900/80">Mark this order as sent when you have handed it to the buyer or delivery provider.</p><button type="button" disabled={actionLoading} onClick={() => void markAsPendingDelivery(selected)} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-zinc-950 px-4 py-2.5 text-sm font-extrabold text-white disabled:opacity-50"><Send className="h-4 w-4" />{actionLoading ? "Updating…" : "Mark as sent"}</button></div> : null}{isDelivered(selected) ? <div className="mt-5 inline-flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-2.5 text-sm font-extrabold text-emerald-900"><CheckCircle2 className="h-4 w-4" /> Delivery completed</div> : null}</section></div></main>;
  }
  return <main className="min-h-screen bg-zinc-50 px-4 py-6 md:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-zinc-400">Seller Workspace</p><h1 className="mt-1 text-3xl font-black text-zinc-950">Seller Orders</h1><p className="mt-1 text-sm text-zinc-500">Manage purchases made from your listings and respond to order disputes in the same workspace.</p></div><button type="button" onClick={() => void loadOrders(true)} className="inline-flex items-center gap-2 rounded-xl border border-zinc-200 bg-white px-3 py-2 text-xs font-bold text-zinc-700 hover:bg-zinc-50"><RefreshCw className={`h-4 w-4 ${refreshing ? "animate-spin" : ""}`} /> Refresh</button></div>
  {pendingDisputes.length > 0 ? <section className="mt-6 rounded-3xl border border-amber-200 bg-amber-50 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-amber-700" /><h2 className="text-lg font-black text-amber-950">Pending Disputes</h2><span className="rounded-full bg-amber-200 px-2.5 py-1 text-xs font-black text-amber-900">{pendingDisputes.length}</span></div><p className="mt-1 text-sm text-amber-900/80">Review buyer requests before continuing delivery or settlement actions.</p></div><button type="button" onClick={() => { setFilter("disputed"); setDisputedFilter("pending"); }} className="rounded-xl border border-amber-300 bg-white px-3 py-2 text-xs font-extrabold text-amber-900 hover:bg-amber-100">View pending disputes</button></div><div className="mt-4 space-y-2">{pendingDisputes.slice(0, 5).map((bundle) => <button key={bundle.order.id} type="button" onClick={() => openOrder(bundle)} className="group w-full rounded-2xl border border-amber-200 bg-white p-4 text-left transition hover:border-amber-300 hover:shadow-sm"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><p className="truncate text-sm font-black text-zinc-950">{bundle.order.items[0]?.title ?? "Order"}</p><p className="mt-1 text-xs text-zinc-500">{bundle.order.id} · {bundle.order.buyerDetails?.fullName ?? "Buyer"}</p></div><div className="flex items-center gap-3"><div className="text-right"><p className="text-[10px] font-extrabold uppercase tracking-wider text-amber-700">{requestedResolutionLabel(bundle.dispute?.requestedResolution ?? bundle.dispute?.latestAttempt?.requestedResolution ?? bundle.refundRequest?.requestedResolution)}</p><p className="mt-1 text-xs font-semibold text-zinc-500">{money(bundle.order)}</p></div><ChevronRight className="h-4 w-4 text-amber-600" /></div></div></button>)}</div></section> : null}
  <div className="mt-6 flex gap-2 overflow-x-auto pb-2">{FILTERS.map((item) => { const count = getFilterCount(orders, item.key, disputedFilter); return <button key={item.key} type="button" onClick={() => { setFilter(item.key); if (item.key !== "disputed") setDisputedFilter("all"); }} className={`inline-flex items-center gap-2 whitespace-nowrap rounded-full px-4 py-2 text-xs font-extrabold transition ${filter === item.key ? "bg-zinc-950 text-white" : "bg-white text-zinc-600 ring-1 ring-zinc-200 hover:bg-zinc-100"}`}>{item.label}<span className={`rounded-full px-1.5 py-0.5 text-[10px] ${filter === item.key ? "bg-white/15 text-white" : "bg-zinc-100 text-zinc-500"}`}>{count}</span></button>; })}</div>
  {filter === "disputed" ? <div className="mt-3 flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="Dispute status"><button type="button" role="tab" aria-selected={disputedFilter === "all"} onClick={() => setDisputedFilter("all")} className={`rounded-xl px-4 py-2 text-xs font-black ${disputedFilter === "all" ? "bg-zinc-900 text-white" : "bg-white text-zinc-600 ring-1 ring-zinc-200"}`}>All <span className="ml-1 opacity-70">{getFilterCount(orders, "disputed", "all")}</span></button><button type="button" role="tab" aria-selected={disputedFilter === "pending"} onClick={() => setDisputedFilter("pending")} className={`rounded-xl px-4 py-2 text-xs font-black ${disputedFilter === "pending" ? "bg-amber-100 text-amber-900" : "bg-white text-zinc-600 ring-1 ring-zinc-200"}`}>Pending <span className="ml-1 opacity-70">{getFilterCount(orders, "disputed", "pending")}</span></button><button type="button" role="tab" aria-selected={disputedFilter === "settled"} onClick={() => setDisputedFilter("settled")} className={`rounded-xl px-4 py-2 text-xs font-black ${disputedFilter === "settled" ? "bg-emerald-100 text-emerald-900" : "bg-white text-zinc-600 ring-1 ring-zinc-200"}`}>Settled <span className="ml-1 opacity-70">{getFilterCount(orders, "disputed", "settled")}</span></button></div> : null}
  {error ? <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700"><div className="flex items-center gap-2"><AlertTriangle className="h-4 w-4" />{error}</div></div> : null}{loading ? <div className="mt-8 rounded-3xl border border-zinc-200 bg-white p-10 text-center text-sm font-semibold text-zinc-500">Loading seller orders…</div> : filteredOrders.length === 0 ? <div className="mt-8 rounded-3xl border border-zinc-200 bg-white p-10 text-center"><Package className="mx-auto h-8 w-8 text-zinc-300" /><p className="mt-3 font-extrabold text-zinc-800">No orders in this view.</p></div> : <div className="mt-5 space-y-3">{filteredOrders.map((bundle) => <button key={bundle.order.id} type="button" onClick={() => openOrder(bundle)} className="group w-full rounded-2xl border border-zinc-200 bg-white p-4 text-left shadow-sm transition hover:border-zinc-300 hover:shadow-md"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><p className="truncate text-sm font-black text-zinc-950">{bundle.order.items[0]?.title ?? "Order"}</p><p className="mt-1 text-xs text-zinc-500">{bundle.order.id} · {bundle.order.buyerDetails?.fullName ?? "Buyer"}</p></div><div className="flex items-center gap-3"><div className="text-right"><p className="text-sm font-black text-zinc-950">{money(bundle.order)}</p><p className="mt-1 text-[10px] font-extrabold uppercase tracking-wider text-zinc-400">{orderStatusLabel(bundle)}</p></div>{isPendingDispute(bundle) ? <ShieldAlert className="h-4 w-4 text-amber-600" /> : null}<ChevronRight className="h-4 w-4 text-zinc-400" /></div></div></button>)}</div>}
  <button type="button" onClick={() => navigateToPath(SELLER_HUB_PATH)} className="mt-8 text-sm font-bold text-zinc-500 hover:text-zinc-950">Back to Workspace</button></div></main>;
}