function buildLifecycleSteps(payment?: PaymentRow | null, webhook?: WebhookEventRow | null, payout?: PayoutRow | null): LifecycleStep[] {
  const isEventPayout = Boolean(payout?.eventId);
  const hasPayment = !!payment;
  const hasCheckout = !!payment?.checkout_url;
  const hasWebhook = !!webhook;
  const hasValidWebhook = webhook ? Number(webhook.signature_valid) === 1 : false;
  const isPaid = !!payment && (["paid", "captured", "success"].includes(token(payment.payment_status)) || !!payment.paid_at);
  const isEscrowActive = !!payment && (["in_escrow", "paid"].includes(token(payment.order_status)) || !!payment.escrow_id);
  const isDelivered = !!payment && token(payment.order_status) === "fulfilled";
  const isSettled = !!payment && ["released", "refunded"].includes(token(payment.escrow_state));
  const isDisputed = !!payment && token(payment.escrow_state) === "disputed";
  const hasPayout = !!payout;
  const destinationVerified = !!payout && token(payout.destinationVerificationStatus) === "verified" && payout.destinationActive !== false;
  const payoutProcessing = !!payout && ["queued", "processing", "pending", "held"].includes(token(payout.status));
  const payoutComplete = !!payout && token(payout.status) === "paid";

  if (isEventPayout) {
    return [
      { number: 1, title: "Checkout created", detail: hasPayment ? "BuyMesho stored a payment row for this checkout attempt." : "No payment row exists yet.", state: hasPayment ? "done" : "waiting", timestamp: payment?.created_at, dbRecord: payment?.id, externalRef: payment?.reference },
      { number: 2, title: "Payment completed", detail: hasCheckout ? "The buyer was sent to the provider checkout URL." : "Waiting for checkout creation.", state: hasCheckout ? "done" : hasPayment ? "active" : "waiting", timestamp: payment?.paid_at, dbRecord: payment?.id, externalRef: payment?.provider_reference },
      { number: 3, title: "Webhook received", detail: hasWebhook ? "PayChangu callback delivery was captured." : "No webhook event has arrived yet.", state: hasWebhook ? "active" : "waiting", timestamp: webhook?.created_at, dbRecord: webhook?.id ? String(webhook.id) : undefined, externalRef: webhook?.reference },
      { number: 4, title: "Payment verified", detail: hasValidWebhook ? "Webhook signature passed verification." : hasWebhook ? "Webhook arrived, but verification has not passed yet." : "Waiting for a verified payment callback.", state: hasValidWebhook ? "done" : hasWebhook ? "issue" : "waiting", timestamp: webhook?.created_at, dbRecord: webhook?.id ? String(webhook.id) : undefined, externalRef: webhook?.reference, error: hasWebhook && !hasValidWebhook ? "Invalid or missing signature" : null },
      { number: 5, title: "Order marked paid", detail: isPaid ? "The ticket order was marked paid." : "The ticket order is still pending confirmation.", state: isPaid ? "done" : "waiting", timestamp: payment?.order_paid_at, dbRecord: payment?.order_id, externalRef: payment?.reference },
      { number: 6, title: "Payout generated", detail: hasPayout ? "A direct event payout record exists for this ticket transaction." : "No event payout row has been linked yet.", state: hasPayout ? "done" : "waiting", timestamp: payout?.createdAt, dbRecord: payout?.id, externalRef: payout?.providerReference },
      { number: 7, title: "Destination verified", detail: destinationVerified ? "The event payout destination is verified and active." : hasPayout ? "Destination still needs verification or activation." : "No payout destination context yet.", state: destinationVerified ? "done" : hasPayout ? "issue" : "waiting", timestamp: payout?.updatedAt, dbRecord: payout?.destinationAccountId ?? undefined, externalRef: payout?.destinationMaskedAccount ?? undefined, error: hasPayout && !destinationVerified ? toText(payout?.destinationLastError, "Destination unverified") : null },
      { number: 8, title: "PayChangu transfer", detail: payoutComplete ? "The event creator payout has completed successfully." : payoutProcessing ? "The payout is moving through the provider flow." : hasPayout ? "The payout is not finished yet." : "No payout to process.", state: payoutComplete ? "done" : payoutProcessing ? "active" : hasPayout ? "issue" : "waiting", timestamp: payout?.latestAttemptAt ?? payout?.sentAt ?? payout?.updatedAt, dbRecord: payout?.id, externalRef: payout?.providerTransactionId ?? payout?.providerReference, error: payout?.latestAttemptFailureReason ?? payout?.lastError },
      { number: 9, title: "Event creator paid", detail: hasPayout && payoutComplete ? "The event creator payout path is fully closed out." : hasPayout ? "The event creator payout path is still open." : "The event payout has not been generated yet.", state: hasPayout && payoutComplete ? "done" : "waiting", timestamp: payout?.paidAt, dbRecord: payout?.id, externalRef: payout?.providerTransactionId ?? payout?.providerReference },
    ];
  }

  return [
    { number: 1, title: "Checkout created", detail: hasPayment ? "BuyMesho stored a payment row for this checkout attempt." : "No payment row exists yet.", state: hasPayment ? "done" : "waiting", timestamp: payment?.created_at, dbRecord: payment?.id, externalRef: payment?.reference },
    { number: 2, title: "Payment completed", detail: hasCheckout ? "The buyer was sent to the provider checkout URL." : "Waiting for checkout creation.", state: hasCheckout ? "done" : hasPayment ? "active" : "waiting", timestamp: payment?.paid_at, dbRecord: payment?.id, externalRef: payment?.provider_reference },
    { number: 3, title: "Webhook received", detail: hasWebhook ? "PayChangu callback delivery was captured." : "No webhook event has arrived yet.", state: hasWebhook ? "active" : "waiting", timestamp: webhook?.created_at, dbRecord: webhook?.id ? String(webhook.id) : undefined, externalRef: webhook?.reference },
    { number: 4, title: "Webhook verified", detail: hasValidWebhook ? "Webhook signature passed verification." : hasWebhook ? "Webhook arrived, but verification has not passed yet." : "Waiting for a webhook to verify.", state: hasValidWebhook ? "done" : hasWebhook ? "issue" : "waiting", timestamp: webhook?.created_at, dbRecord: webhook?.id ? String(webhook.id) : undefined, externalRef: webhook?.reference, error: hasWebhook && !hasValidWebhook ? "Invalid or missing signature" : null },
    { number: 5, title: "Order marked paid", detail: isPaid ? "The order was marked paid and moved into the confirmed flow." : "The order is still pending confirmation.", state: isPaid ? "done" : "waiting", timestamp: payment?.order_paid_at, dbRecord: payment?.order_id, externalRef: payment?.reference },
    { number: 6, title: "Escrow created", detail: isEscrowActive ? "Funds are represented as active escrow for the order." : "Escrow has not started yet.", state: isEscrowActive ? (isDisputed ? "issue" : "active") : "waiting", timestamp: payment?.escrow_updated_at, dbRecord: payment?.escrow_id ?? undefined, externalRef: payment?.order_id },
    { number: 7, title: "Delivery confirmed", detail: isDelivered ? "The order has been marked fulfilled after delivery confirmation." : "Waiting for delivery confirmation.", state: isDelivered ? "done" : "waiting", timestamp: payment?.order_fulfilled_at, dbRecord: payment?.order_id, externalRef: payment?.escrow_id ?? undefined },
    { number: 8, title: "Escrow released", detail: isSettled ? (token(payment?.escrow_state) === "released" ? "Funds were released to the seller." : "Funds were refunded to the buyer.") : "Final settlement has not happened yet.", state: token(payment?.escrow_state) === "released" ? "done" : token(payment?.escrow_state) === "refunded" ? "issue" : "waiting", timestamp: payment?.escrow_updated_at, dbRecord: payment?.escrow_id ?? undefined, externalRef: payment?.order_id },
    { number: 9, title: "Payout generated", detail: hasPayout ? "A seller payout record exists for this transaction." : "No seller payout row has been linked yet.", state: hasPayout ? "done" : "waiting", timestamp: payout?.createdAt, dbRecord: payout?.id, externalRef: payout?.providerReference },
    { number: 10, title: "Destination verified", detail: destinationVerified ? "The payout destination is verified and active." : hasPayout ? "Destination still needs verification or activation." : "No payout destination context yet.", state: destinationVerified ? "done" : hasPayout ? "issue" : "waiting", timestamp: payout?.updatedAt, dbRecord: payout?.destinationAccountId ?? undefined, externalRef: payout?.destinationMaskedAccount ?? undefined, error: hasPayout && !destinationVerified ? toText(payout?.destinationLastError, "Destination unverified") : null },
    { number: 11, title: "PayChangu transfer", detail: payoutComplete ? "The seller payout has completed successfully." : payoutProcessing ? "The payout is still moving through the settlement flow." : hasPayout ? "The payout is not finished yet." : "No seller payout to process.", state: payoutComplete ? "done" : payoutProcessing ? "active" : hasPayout ? "issue" : "waiting", timestamp: payout?.latestAttemptAt ?? payout?.sentAt ?? payout?.updatedAt, dbRecord: payout?.id, externalRef: payout?.providerTransactionId ?? payout?.providerReference, error: payout?.latestAttemptFailureReason ?? payout?.lastError },
    { number: 12, title: "Seller paid", detail: hasPayout && payoutComplete ? "The payout path is fully closed out." : hasPayout ? "The payout path is still open." : "The transaction has not closed the payout loop yet.", state: hasPayout && payoutComplete ? "done" : "waiting", timestamp: payout?.paidAt, dbRecord: payout?.id, externalRef: payout?.providerTransactionId ?? payout?.providerReference },
  ];
}
